[package]
name = "openbrief-desktop"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
name = "openbrief_desktop"
crate-type = ["lib", "cdylib", "staticlib"]

[[bin]]
name = "openbrief-desktop"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2.5.6", features = [] }

[dependencies]
openbrief-app = { path = "../../../crates/openbrief-app" }
openbrief-client = { path = "../../../crates/openbrief-client" }
openbrief-protocol = { path = "../../../crates/openbrief-protocol" }
tauri = { version = "2.11.5", features = [] }
tokio.workspace = true

[features]
custom-protocol = [ "tauri/custom-protocol" ]

[lints]
workspace = true
